version: '3.8'

services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"       # Public HTTP Port
      - "443:443"     # Public HTTPS Port
      - "8090:81"     # Admin Web Port for Nginx Proxy Manager
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx main configuration file
      - ./letsencrypt:/etc/letsencrypt  # Mount Let's Encrypt SSL certificates
    depends_on:
      - frontend
      - backend
      - adminer
    networks:
      - mynet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"   # Adjust as per your frontend port
    networks:
      - mynet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"   # Adjust as per your backend port
    networks:
      - mynet

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
